apiVersion: v1
kind: Secret
metadata:
  name: onlyoffice-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "onlyoffice.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
