apiVersion: v1
kind: Service
metadata:
  name: onlyoffice
  namespace: {{ .Release.Namespace }}
  labels:
    app: onlyoffice
    {{- include "onlyoffice.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: onlyoffice
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
