apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloudbeaver.name" . }}-workspace
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudbeaver.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
