admin.user=admin
admin.password=admin
admin.readOnlyUser=user
admin.readOnlyPassword=user

dir=/backup/seaweedfs

bucket=velero,logs
s3.config=/etc/seaweedfs/s3-config.json
s3.externalUrl=https://s3-seaweedfs.nexai.org.com