apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flarum.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flarum.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLARUM_ADMIN_PASS: {{ .Values.forum.adminPassword | quote }}
