apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filebrowser.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        {{- include "filebrowser.labels" . | nindent 8 }}
    spec:
      containers:
        - name: filebrowser
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: srv
              mountPath: /srv
            - name: db
              mountPath: /home/filebrowser/data
            - name: config
              mountPath: /home/filebrowser/data/config.yaml
              subPath: config.yaml
              readOnly: true
      securityContext:
        fsGroup: 1000
      volumes:
        - name: srv
          persistentVolumeClaim:
            claimName: {{ include "filebrowser.name" . }}-srv
        - name: db
          persistentVolumeClaim:
            claimName: {{ include "filebrowser.name" . }}-db
        - name: config
          configMap:
            name: {{ include "filebrowser.name" . }}-config
